config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

   # add this line to link tags to posts with the respective tag
  get 'tags/:tag', to: 'posts#index', as: :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    params[:tag] ? @posts = Post.tagged_with(params[:tag]) : @posts = Post.all
  end
 
  def show
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end
  private
def post_params
    params.require(:post).permit(:title, :content, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <script>
  jQuery(document).on('turbolinks:load', function () {
    jQuery('#post_tag_ids').chosen({
      allow_single_deselect: true,
      width: '100%'
    })
  });
</script>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<div class = "col-md-8 offset-2">
  <% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <p><%= truncate(post.content, length: 50) %></p>
    <p><small>Tags: <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small</p>
    <p><%= link_to "Read Post", post_path(post) %></p>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class = 'col-md-8 offset-2'>
  <h1 class = "text-center">New Blog Post</h1>
  <%= simple_form_for @post, url: posts_path do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :tag_ids, as: :select, collection: Tag.order(:name), label_method: :name, input_html: {multiple: true} %>
    <%= f.submit "Next", class: 'btn btn-lg btn-primary float-right' %>

  <% end %>
</div>

 <script>
  jQuery(document).on('turbolinks:load', function () {
    jQuery('#post_tag_ids').chosen({
      allow_single_deselect: true,
      width: '100%'
    })
  });
</script>

app/views/posts/show.html.erb
<div class = 'col-md-8 offset-2'>
  <h1><%=@post.title%></h1>
  <p><%=@post.content%></p>
  <p><small>Tags: <%= raw @post.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small</p>
</div>